# frozen_string_literal: true

require "test_helper"
require "generators/fox_tail/themes_generator"

class ThemesGeneratorTest < Rails::Generators::TestCase
  tests FoxTail::ThemesGenerator
  destination File.expand_path("../../../tmp/generators", __FILE__)
  setup :prepare_destination

  def test_copy_all # rubocop:disable Minitest/MultipleAssertions
    run_generator

    assert_file "app/components/fox_tail/accordion_component.theme.yml"
    assert_file "app/components/fox_tail/alert_component.theme.yml"
    assert_file "app/components/fox_tail/avatar_component.theme.yml"
    assert_file "app/components/fox_tail/avatar_stack_component.theme.yml"
    assert_file "app/components/fox_tail/badge_component.theme.yml"
    assert_file "app/components/fox_tail/button_base_component.theme.yml"
    assert_file "app/components/fox_tail/button_component.theme.yml"
    assert_file "app/components/fox_tail/button_group_component.theme.yml"
    assert_file "app/components/fox_tail/carousel_component.theme.yml"
    assert_file "app/components/fox_tail/checkbox_component.theme.yml"
    assert_file "app/components/fox_tail/collapsible_component.theme.yml"
    assert_file "app/components/fox_tail/collapsible_trigger_component.theme.yml"
    assert_file "app/components/fox_tail/dialog_component.theme.yml"
    assert_file "app/components/fox_tail/dismissible_component.theme.yml"
    assert_file "app/components/fox_tail/dot_indicator_component.theme.yml"
    assert_file "app/components/fox_tail/drawer_component.theme.yml"
    assert_file "app/components/fox_tail/drawer_trigger_component.theme.yml"
    assert_file "app/components/fox_tail/dropdown_component.theme.yml"
    assert_file "app/components/fox_tail/dropdown_trigger_component.theme.yml"
    assert_file "app/components/fox_tail/dropzone_component.theme.yml"
    assert_file "app/components/fox_tail/fab_component.theme.yml"
    assert_file "app/components/fox_tail/file_input_component.theme.yml"
    assert_file "app/components/fox_tail/helper_text_component.theme.yml"
    assert_file "app/components/fox_tail/hr_component.theme.yml"
    assert_file "app/components/fox_tail/icon_button_component.theme.yml"
    assert_file "app/components/fox_tail/icon_component.theme.yml"
    assert_file "app/components/fox_tail/input_base_component.theme.yml"
    assert_file "app/components/fox_tail/input_component.theme.yml"
    assert_file "app/components/fox_tail/input_error_list_component.theme.yml"
    assert_file "app/components/fox_tail/input_group_component.theme.yml"
    assert_file "app/components/fox_tail/label_component.theme.yml"
    assert_file "app/components/fox_tail/link_component.theme.yml"
    assert_file "app/components/fox_tail/modal_component.theme.yml"
    assert_file "app/components/fox_tail/pagination_component.theme.yml"
    assert_file "app/components/fox_tail/popover_component.theme.yml"
    assert_file "app/components/fox_tail/progress_bar_component.theme.yml"
    assert_file "app/components/fox_tail/range_component.theme.yml"
    assert_file "app/components/fox_tail/spinner_component.theme.yml"
    assert_file "app/components/fox_tail/stepper_component.theme.yml"
    assert_file "app/components/fox_tail/surface_component.theme.yml"
    assert_file "app/components/fox_tail/table_component.theme.yml"
    assert_file "app/components/fox_tail/tabs_component.theme.yml"
    assert_file "app/components/fox_tail/timeline_component.theme.yml"
    assert_file "app/components/fox_tail/toast_component.theme.yml"
    assert_file "app/components/fox_tail/toggle_component.theme.yml"
    assert_file "app/components/fox_tail/tooltip_component.theme.yml"
  end

  def test_selected_components # rubocop:disable Minitest/MultipleAssertions
    run_generator %w[-c alert avatar modal]

    assert_no_file "app/components/fox_tail/accordion_component.theme.yml"
    assert_file "app/components/fox_tail/alert_component.theme.yml"
    assert_file "app/components/fox_tail/avatar_component.theme.yml"
    assert_no_file "app/components/fox_tail/avatar_stack_component.theme.yml"
    assert_no_file "app/components/fox_tail/badge_component.theme.yml"
    assert_no_file "app/components/fox_tail/button_base_component.theme.yml"
    assert_no_file "app/components/fox_tail/button_component.theme.yml"
    assert_no_file "app/components/fox_tail/button_group_component.theme.yml"
    assert_no_file "app/components/fox_tail/carousel_component.theme.yml"
    assert_no_file "app/components/fox_tail/checkbox_component.theme.yml"
    assert_no_file "app/components/fox_tail/collapsible_component.theme.yml"
    assert_no_file "app/components/fox_tail/collapsible_trigger_component.theme.yml"
    assert_no_file "app/components/fox_tail/dialog_component.theme.yml"
    assert_no_file "app/components/fox_tail/dismissible_component.theme.yml"
    assert_no_file "app/components/fox_tail/dot_indicator_component.theme.yml"
    assert_no_file "app/components/fox_tail/drawer_component.theme.yml"
    assert_no_file "app/components/fox_tail/drawer_trigger_component.theme.yml"
    assert_no_file "app/components/fox_tail/dropdown_component.theme.yml"
    assert_no_file "app/components/fox_tail/dropdown_trigger_component.theme.yml"
    assert_no_file "app/components/fox_tail/dropzone_component.theme.yml"
    assert_no_file "app/components/fox_tail/fab_component.theme.yml"
    assert_no_file "app/components/fox_tail/file_input_component.theme.yml"
    assert_no_file "app/components/fox_tail/helper_text_component.theme.yml"
    assert_no_file "app/components/fox_tail/hr_component.theme.yml"
    assert_no_file "app/components/fox_tail/icon_button_component.theme.yml"
    assert_no_file "app/components/fox_tail/icon_component.theme.yml"
    assert_no_file "app/components/fox_tail/input_base_component.theme.yml"
    assert_no_file "app/components/fox_tail/input_component.theme.yml"
    assert_no_file "app/components/fox_tail/input_error_list_component.theme.yml"
    assert_no_file "app/components/fox_tail/input_group_component.theme.yml"
    assert_no_file "app/components/fox_tail/label_component.theme.yml"
    assert_no_file "app/components/fox_tail/link_component.theme.yml"
    assert_file "app/components/fox_tail/modal_component.theme.yml"
    assert_no_file "app/components/fox_tail/pagination_component.theme.yml"
    assert_no_file "app/components/fox_tail/popover_component.theme.yml"
    assert_no_file "app/components/fox_tail/progress_bar_component.theme.yml"
    assert_no_file "app/components/fox_tail/range_component.theme.yml"
    assert_no_file "app/components/fox_tail/spinner_component.theme.yml"
    assert_no_file "app/components/fox_tail/stepper_component.theme.yml"
    assert_no_file "app/components/fox_tail/surface_component.theme.yml"
    assert_no_file "app/components/fox_tail/table_component.theme.yml"
    assert_no_file "app/components/fox_tail/tabs_component.theme.yml"
    assert_no_file "app/components/fox_tail/timeline_component.theme.yml"
    assert_no_file "app/components/fox_tail/toast_component.theme.yml"
    assert_no_file "app/components/fox_tail/toggle_component.theme.yml"
    assert_no_file "app/components/fox_tail/tooltip_component.theme.yml"
  end
end
